services:
  - type: web
    name: youtube-trend205
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: GMAIL_RECIPIENT
        sync: false
      - key: GMAIL_SENDER
        sync: false
      - key: GMAIL_CREDENTIALS_JSON
        sync: false
      - key: GMAIL_TOKEN_JSON
        sync: false
